PEX.CustomerPayment.Presentation/ViewModels/TerminosYCondicionesVIewModel.cs
using PEX.CustomerPayment.Presentation.Helpers;
using PEX.CustomerPayment.Presentation.Models.General;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PEX.CustomerPayment.Presentation.ViewModels
{
    public class TerminosYCondicionesVIewModel
    {
        public string TerminosYCondiciones { get; set; }


        internal void Fill(CargarDatosContext cargarDatosContext)
        {
            TerminosYCondiciones = cargarDatosContext.contextSql.ParametroConfiguracion.Where(x => x.CodigoParametro == ConstantHelpers.ParametroConfiguracion.Codigo_Terminos_Condiciones_Solicitud_Pago && x.FechaCaducidad == null).Select(x => x.ValorParametro).FirstOrDefault();
        }
    }
}

PEX.CustomerPayment.Presentation/Controllers/SolicitudController.cs
using PEX.CustomerPayment.Presentation.Logica;
using PEX.CustomerPayment.Presentation.Servicios.Sms;
using PEX.CustomerPayment.Presentation.ViewModels;
using System;
using System.Web.Mvc;

namespace PEX.CustomerPayment.Presentation.Controllers
{
    public class SolicitudController : BaseController
    {
        public ActionResult ConsultarReferencia()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConsultarReferencia(ConsultaReferenciaViewModel model)
        {
            try
            {
                var solicitudId = model.Register(CargarDatosContext());
                return RedirectToAction("MostrarDatosSolicitud", new { solicitudId });
            }
            catch (Exception ex)
            {
                PostMessage(HelperKit.Mvc.MessageType.Danger, "No se ha encontrado una operación con el número de referencia ingresado");
                return View(model);
            }
            
        }


        public ActionResult MostrarDatosSolicitud(Guid solicitudId)
        {
            DatosSoliitudViewModel model = new DatosSoliitudViewModel();
            model.Fill(CargarDatosContext(), solicitudId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult MostrarDatosSolicitud(DatosSoliitudViewModel model)
        {
            try
            {
                model.Register(CargarDatosContext(), Server.MapPath("~/EmailTemplates"));
                return Json(new
                {
                    error = false,
                    message = $"SL{model.SolicitudPago.NumeroReferencia}"
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    error = true,
                    message = ex.Message
                });

            }
        }

        public ActionResult FinalizarSolicitud(Guid solicitudId)
        {
            DatosSoliitudViewModel model = new DatosSoliitudViewModel();
            model.Fill(CargarDatosContext(), solicitudId);
            return View(model);
        }



        public ActionResult ConsultaSeguimiento(Guid ppst)
        {
            return RedirectToAction("MostrarDatosSolicitud", new { solicitudId = ppst });
        }

        public PartialViewResult _TerminosYCondiciones()
        {
            TerminosYCondicionesVIewModel model = new TerminosYCondicionesVIewModel();
            model.Fill(CargarDatosContext());
            return PartialView(model);
        }


        public ActionResult NotificarDeposito(Guid solicitudId)
        {
            DatosSoliitudViewModel model = new DatosSoliitudViewModel();
            model.Fill(CargarDatosContext(), solicitudId);
            model.EndPayment(CargarDatosContext(), Server.MapPath("~/EmailTemplates"));
            return Json(new
            {
                error = false,
                message = $"SL{model.SolicitudPago.NumeroReferencia}"
            });
        }

        public ActionResult Test()
        {
            SmsHandler smsHandler = new SmsHandler();
            smsHandler.SendMessage("Se ha registrado su solicitud. Para ver el estado ingrese a: https://peruexpress.cloud/pagos", "926974280");
            smsHandler.SendMessage("Se ha registrado su solicitud. Para ver el estado ingrese a: https://peruexpress.cloud/pagos", "984153422");
            return View();
        }

        public ActionResult SendEmail()
        {
            try
            {
                EmailSMTPService emailSMTPService = new EmailSMTPService();
                emailSMTPService.SendSingleEmail("vck1805@gmail.com", "TEST", "TEST");
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View();
        }

    }
}

PEX.CustomerPayment.Presentation/Views/Solicitud/ConsultaSeguimiento.cshtml
@model PEX.CustomerPayment.Presentation.ViewModels.DatosSoliitudViewModel

@{
    ViewBag.Title = "Seguimiento de solicitud";
}

PEX.CustomerPayment.Presentation/Views/Solicitud/ConsultarReferencia.cshtml
@model PEX.CustomerPayment.Presentation.ViewModels.ConsultaReferenciaViewModel

@{
    ViewBag.Title = "Solicitud Pago Moneygram";
}

<div class="container">
    <h2 class="font-weight-400 text-center mt-3">Solicitud Pago Moneygram</h2>
    <p class="text-4 text-center mb-4">Ingrese los datos solicitados para realizar una solicitud de Pago MoneyGram</p>
    <div class="row">
        <div class="col-md-8 col-lg-6 col-xl-5 mx-auto">
            <div class="bg-light shadow-sm rounded p-3 p-sm-4 mb-4">
                <h3 class="text-5 font-weight-400 mb-3">Datos de la transacción</h3>
                <!-- Send Money Form
                ============================================= -->
                @using (Html.BeginForm("ConsultarReferencia", "Solicitud", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        @Html.LabelFor(x => Model.NumeroReferencia)
                        @Html.TextBoxFor(x => Model.NumeroReferencia, new { @class = "form-control", placeholder = "Número de referencia de 8 dígitos" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(x => Model.NumeroDocumento)
                        @Html.TextBoxFor(x => Model.NumeroDocumento, new { @class = "form-control", placeholder = "Número de documento de identidad" })
                    </div>
                    <button type="submit" class="btn btn-primary btn-block ladda-button" data-style="expand-right">Continuar <i class="fa fa-arrow-right"></i></button>
                }
                <!-- Send Money Form end -->
            </div>
            <a href="#" @Data.ModalLink("_TerminosYCondiciones")>Términos y condiciones</a>
        </div>
    </div>
</div>

PEX.CustomerPayment.Presentation/Views/Solicitud/FinalizarSolicitud.cshtml
@model PEX.CustomerPayment.Presentation.ViewModels.DatosSoliitudViewModel
@{
    ViewBag.Title = "Finalizar solicitud";
}

<div class="container">
    <h2 class="font-weight-400 text-center mt-3 mb-4">Solicitud de pago</h2>
    <div class="row">
        <div class="col-md-8 col-lg-6 col-xl-5 mx-auto">
            <!-- Send Money Success
            ============================================= -->
            <div class="bg-light shadow-sm rounded p-3 p-sm-4 mb-4">
                <div class="text-center my-5">
                    <p class="text-center text-success text-20 line-height-07"><i class="fas fa-check-circle"></i></p>
                    <p class="text-center text-success text-8 line-height-07">Éxito!</p>
                    <p class="text-center text-4">Se ha registrado su solicitud correctamente</p>
                </div>
                <p class="text-center text-3 mb-4">Si necesitamos verificar alguno de sus datos uno de nuestros asesores se comunicará con usted al número celular y correo brindado. Su código de solicitud es el siguiente: <span class="text-4 font-weight-500"> @("SL" + Model.SolicitudPago.NumeroReferencia)</span> </p>
                <a class="btn btn-primary btn-block" href="@Url.Action("ConsultarReferencia","Solicitud")">Regresar al inicio</a>
                @*<button class="btn btn-link btn-block"><i class="fas fa-print"></i> Print</button>*@
            </div>
        </div>
    </div>
</div>

PEX.CustomerPayment.Presentation/Views/Solicitud/_TerminosYCondiciones.cshtml
@model PEX.CustomerPayment.Presentation.ViewModels.TerminosYCondicionesVIewModel


@{
    ViewBag.Title = "Términos y condiciones";
    Layout = "~/Views/Shared/_ModalLayout.cshtml";
}

@*<h2>Términos y condiciones</h2>*@


@Html.Raw(Model.TerminosYCondiciones)